#ifndef __BINGO_H_
#define __BINGO_H_

char *calls[] = { "",
"At the beginning",
"One little duck",
"Debbie McGee",
"Bobby Moore",
"Man alive",
"Chopsticks",
"Lucky for some",
"One fat lady",
"Doctor's orders",
"Downing street",
"Legs - they're lovely",
"Monkey's cousin",
"Unlucky for some",
"Valentines day",
"Rugby team",
"Never been kissed",
"Often been kissed",
"Key of the door",
"Goodbye teens",
"One score",
"Royal salute",
"Two little ducks",
"The Lord is my Shepherd",
"Two dozen",
"Duck and dive",
"Bed and breakfast",
"Gateway to heaven",
"Duck & its mate",
"In your prime",
"Your face is dirty",
"Get up and run",
"Buckle my Shoe",
"All the threes",
"Ask for more",
"Jump and jive",
"Three dozen",
"More than eleven",
"Christmas cake",
"All the steps",
"Two score",
"Time for fun",
"That famous street in Manhattan",
"Down on your knees",
"Droopy drawers",
"Halfway house",
"Up to tricks",
"Four and seven",
"Four dozen",
"Rise and shine",
"Bulls eye",
"The Highland Division",
"Danny La Rue",
"The joker",
"House of bamboo",
"Snakes alive",
"Was she worth it?",
"Heinz varieties",
"Choo choo Thomas",
"Brighton line",
"Three score",
"Bakers bun",
"Tickety boo",
"Tickle me",
"The Beatles number",
"Old age pension",
"Clickety click",
"Made in heaven",
"Saving grace",
"Meal for two",
"Three score and ten",
"Bang on the drum",
"Par for the course",
"Queen Bee",
"Candy store",
"Big Daddy",
"Trombones",
"All the sevens",
"Heavens gate",
"One more time",
"Gandhi's breakfast",
"Stop and run",
"Fat lady with a duck",
"Time for tea",
"Seven dozen",
"Staying alive",
"Between the sticks",
"Torquay in Devon",
"Two fat ladies",
"Nearly there",
"Top of the house"
};

#endif
